version: "3.7"

services:  
  Database:
    image: mariadb
    container_name: test-ph-sl-db
    environment:
      MYSQL_ROOT_PASSWORD: 123root
      MYSQL_DATABASE: test-shoppinglist
    ports:
      - "15906:3306"